### ISSUE TITLE
(Bug) Undesired `(((NEW LINE)))` added to generated localization

### ISSUE THREAD

**Issue by jzapdot** [YarnSpinnerTool/YarnSpinner-Unity#116] opened 2021-08-26 14:46 UTC
## What is the current behavior?

When generating localization, some lines/options are having a `(((NEW LINE)))` text added to the end of the locale and I have no idea what prompts this. In this example, the option does not show any new line character and does not continue onto the next line.

![image](https://user-images.githubusercontent.com/40764984/130984274-93ac124d-9466-4fe6-ac89-493eaceb626e.png)

In the loc however a `(((NEW LINE)))` is present.

![image](https://user-images.githubusercontent.com/40764984/130984444-9cc4f27b-d2e3-4a58-89be-a7c085d8752d.png)

## Please provide the steps to reproduce, and if possible a minimal demo of the problem:

**Example Raw Yarn Script**
```
title: Start
tags: 
colorID: 0
position: -182,-977
---
Hey there #line:028faf4
I see The Rescue sent you a care package! #line:069ef91
You should make use of that #line:014fdc5
[[I’ve only been back for like 24 hours|Node_2]] #line:0afef88
===
title: Node_2
tags: 
colorID: 0
position: -182,-709
---
Hi, this is text on Node_2 #line:060a8fe

[[Node_3]]
===
title: Node_3
tags: 
colorID: 0
position: -180,-460
---
Hi, this is text on Node_3 #line:005e60b
===

```

These files are:
* Being edited in the latest version of the local Yarn Editor.
* Saved as Yarn files to Unity.
* Line Tags generated
* Localization generated.

### Expected
Localization generated includes only player-visible text from Yarn Script.

**Expected localization**
```
id,text,file,node,lineNumber
line:028faf4,Hey there,MultipleNode,Start,6
line:069ef91,I see The Rescue sent you a care package!,MultipleNode,Start,7
line:014fdc5,You should make use of that,MultipleNode,Start,8
line:0afef88,I’ve only been back for like 24 hours,MultipleNode,Start,9
line:060a8fe,"Hi, this is text on Node_2",MultipleNode,Node_2,16
line:005e60b,"Hi, this is text on Node_3",MultipleNode,Node_3,25
```

### Actual
Localization generated includes player-visible text from Yarn Script and a `(((NEW LINE)))`  appended to some lines.

**Actual Localization**
```
id,text,file,node,lineNumber
line:028faf4,Hey there,MultipleNode,Start,6
line:069ef91,I see The Rescue sent you a care package!,MultipleNode,Start,7
line:014fdc5,You should make use of that,MultipleNode,Start,8
line:0afef88,I’ve only been back for like 24 hours (((NEW LINE))),MultipleNode,Start,9
line:060a8fe,"Hi, this is text on Node_2",MultipleNode,Node_2,16
line:005e60b,"Hi, this is text on Node_3",MultipleNode,Node_3,25
```

**Please tell us about your environment:**
  
**Unity:** 2020.3.20f1
**Yarn:** 1.2.0 (based on included package.json).

**Other information**

**Comment by McJones** [comment] 2021-11-03 04:32
Can't reproduce this across a few different versions of Yarn Spinner or Unity.
Does this go away if you use YS from the head of main instead of the version of YS you used?

**Comment by jzapdot** [comment] 2021-11-09 15:36
Hi @McJones, I apologize for the delayed response. We're in the final days to a significant milestone so it may take a week or so to be able to attempt a repro/further investigation.

**Comment by McJones** [comment] 2021-12-13 23:06
There's been no movement on these for a while now, closing them.
Feel free to reopen if the issue persists.

**Closed by McJones** 2021-12-13 23:06 UTC
Labels: bug
