### ISSUE TITLE
Braces not removed when display variable in view

### ISSUE THREAD

**Issue by unknowndevice** [YarnSpinnerTool/YarnSpinner-Unity#56] opened 2020-11-12 01:26 UTC
**What is the current behavior?**

when you display a declared variable the braces are not removed when you get the text in the view.

**Please provide the steps to reproduce, and if possible a minimal demo of the problem**:

<<declare $problems = 0>>
Speaker: I've got {$problems} problems!

// This will print "I've got {0} problems!

**What is the expected behavior?**

It should display the variable value without the braces

**Please tell us about your environment:**
  
  - Yarn Spinner Version:  v2.0.0-beta1
  - Unity Version: 2020.1.12f1

<img width="695" alt="Screenshot 2020-11-12 at 01 26 23" src="https://user-images.githubusercontent.com/4682853/98883399-16b35080-2486-11eb-8fe0-b968593c2d75.png">

**Comment by unknowndevice** [comment] 2020-11-12 01:38
I think this is a duplicate of #35

**Comment by desplesda** [comment] 2020-11-19 02:38
I suspect this is a duplicate of #35 too - the unit tests I added in 284fd60accad852aaf6b34cdcbbd5cc9f7033954 don't show this behaviour, and I think that the `{0}` that you're seeing there is actually a coincidence (you set `$problems` to zero, but that's not the reason why it was rendering as `{0}`.)

Going to close this here; let me know if I need to re-open!

**Closed by desplesda** 2020-11-19 02:38 UTC
