### ISSUE TITLE
baseLocalisationStringTable is not created if program has no strings

### ISSUE THREAD

**Issue by Farbs** [YarnSpinnerTool/YarnSpinner-Unity#22] opened 2020-07-22 14:18 UTC
I'm using a YarnProgram to set some initial variables. This program does not include any strings.

When I start the game this program is run, however it throws the following exception:

UnassignedReferenceException: The variable baseLocalisationStringTable of YarnProgram has not been assigned.
You probably need to assign the baseLocalisationStringTable variable of the YarnProgram script in the inspector.
Yarn.Unity.DialogueRunner.AddStringTable (YarnProgram yarnScript) (at Assets/YarnSpinner/Runtime/DialogueRunner.cs:201)
Yarn.Unity.DialogueRunner.CreateDialogueInstance () (at Assets/YarnSpinner/Runtime/DialogueRunner.cs:585)
Yarn.Unity.DialogueRunner.get_Dialogue () (at Assets/YarnSpinner/Runtime/DialogueRunner.cs:143)
Yarn.Unity.DialogueRunner.Start () (at Assets/YarnSpinner/Runtime/DialogueRunner.cs:542)

I can work around this by adding an unused node with a string.
  
  - Yarn Spinner Version: 
[v1.2.6]

  - Unity Version:
2019.2.0f1

**Comment by janmaslov** [comment] 2020-07-22 17:45
Hi!

This is a duplicate of #12. Same fix.

**Closed** 2020-07-23 01:14 UTC
Labels: bug
