### ISSUE TITLE
AddActionsFromAssemblies from ActionManager is causing build to crash on Android (from Unity)

### ISSUE THREAD

**Issue by juancabrera** [YarnSpinnerTool/YarnSpinner-Unity#211] opened 2022-11-15 22:56 UTC
**What is the current behavior?**
Yarn Spinner works as expected in Unity's editor. But when you build to Android with a custom yarn project and script the build will crash at the start.

**Please provide the steps to reproduce, and if possible a minimal demo of the problem**:
1. Create a custom Yarn Project with a custom Script so it will call the `SetProject` from `DialogueRunner` class
2. Build to an Android device (I'm using Quest 2 but it seems the issue happens with Windows and other Android devices)
3. Build will crash at the start.

**What is the expected behavior?**
1. not to crash
2. maybe find a way that yarn spinner can work fine in Unity without all this looking for every single assembly and its methods and commands.

**Please tell us about your environment:**
  
  - Yarn Spinner Version: `Version 2.2.3 `
  - Unity Version: `2021.3.5f1`

**Other information** 
* The method causing the build to crash is `AddActionsFromAssemblies` that then calls `FindAllActions` from `ActionManager`, it seems that going through every single assembly and all its methods (16k approx in my project) is causing the build to crash. I'm not exactly sure why this super expensive method is required for Yarn Spinner to work on Unity.
* One way to get the builds to run is to change the "IL2CPP" options on build setting to "Faster (smaller) builds", or commenting out all this work looking for assemblies methods and commands.

**Comment by McJones** [comment] 2023-01-17 01:00
This is a duplicate of #163. Will follow up on that issue.

**Closed by McJones** 2023-01-17 01:00 UTC
Labels: bug
