### ISSUE TITLE
WebGL runtime exception

### ISSUE THREAD

**Issue by slonoed** [YarnSpinnerTool/YarnSpinner-Unity#163] opened 2022-03-05 03:12 UTC
**What is the current behavior?**
Yarn Unity (2.1.0) throws exception when running WebGL build.
`null function or function signature mismatch`
Full stacktrace below

**Please provide the steps to reproduce, and if possible a minimal demo of the problem**:
1. Follow Yarn docs https://docs.yarnspinner.dev/using-yarnspinner-with-unity/quick-start 2. 
2. Build for WebGL
3. Run in browser (chrome, safari) 

Repo with bug: https://github.com/slonoed/yarn_issue

**What is the expected behavior?**
Do not fail

**Please tell us about your environment:**
  
  - Yarn Spinner Version: 2.1.0
  - Unity Version: 2021.2.14f (and other 2021.2).
  - Macos (M1) and Widnows

**Other information** 

```
Uncaught RuntimeError: null function or function signature mismatch
    at il2cpp::vm::InvokeDelegateConstructor(Il2CppDelegate*, Il2CppObject*, MethodInfo const*) (web.wasm:0xe30d4)
    at Delegate_CreateDelegate_internal_mBA6CFDB235B7F91DBAAD074AF07DA167291E3872 (web.wasm:0x1700992)
    at Delegate_CreateDelegate_mE57A1F8CC813EF670D026C17D2D4CFD7C6E3F40A (web.wasm:0x1701376)
    at Delegate_CreateDelegate_m846D4CDDE47C5D98CC5B5CB0292E308D3EC67EC7 (web.wasm:0x17013c9)
    at Delegate_CreateDelegate_mA2E221A01A8B3FBEC4C8A529F3C213C60A3A2C53 (web.wasm:0x17013d8)
    at RuntimeMethodInfo_CreateDelegate_m026E9DD922CC53D92EA3A3529A1BC089ABD0B8B9 (web.wasm:0x160e2aa)
    at ActionManager_GetFunctionRunner_m7BB545776DC22611A918361CC0FCBD07B9EEB7E9 (web.wasm:0x1283374)
    at dynCall_iii (web.wasm:0x1976a43)
    at web.framework.js:1036:20
    at invoke_iii (web.framework.js:14749:10)
    at ActionManager_FindAllActions_m7DE3020C8F3476B34990442939FD237BC049289A (web.wasm:0x1284a13)
    at ActionManager_AddActionsFromAssemblies_mCC3AC961DB087BA139C9D46E33448CBC7E5514F7 (web.wasm:0x12860d5)
    at DialogueRunner_SetProject_m8507254C36C972E8C378E529B015D1AB29125A5F (web.wasm:0x1287e50)
    at DialogueRunner_Start_mDB146186494B91F0EEA6C010E6687C8DED346C12 (web.wasm:0x1288ceb)
    at RuntimeInvoker_TrueVoid_t4861ACF8F4594C3437BB48B6E56783494B843915(void (*)(), MethodInfo const*, void*, void**, void*) (web.wasm:0x1922c74)
    at il2cpp::vm::Runtime::InvokeWithThrow(MethodInfo const*, void*, void**) (web.wasm:0x1959758)
    at dynCall_iiii (web.wasm:0x1976a0d)
    at web.framework.js:1036:20
    at invoke_iiii (web.framework.js:14782:10)
    at il2cpp::vm::Runtime::Invoke(MethodInfo const*, void*, void**, Il2CppException**) (web.wasm:0x1958bfe)
    at il2cpp_runtime_invoke (web.wasm:0xf8f64)
    at ScriptingInvocation::Invoke(ScriptingExceptionPtr*, bool) (web.wasm:0x8c757a)
    at MonoBehaviour::InvokeMethodOrCoroutineChecked(ScriptingMethodPtr, ScriptingObjectPtr) (web.wasm:0x8c2e74)
    at MonoBehaviour::DelayedStartCall(Object*, void*) (web.wasm:0x8c4567)
    at DelayedCallManager::Update(int) (web.wasm:0x195f30)
    at InitPlayerLoopCallbacks()::EarlyUpdateScriptRunDelayedStartupFrameRegistrator::Forward() (web.wasm:0x8a04c4)
    at ExecutePlayerLoop(NativePlayerLoopSystem*) (web.wasm:0x187f53)
    at ExecutePlayerLoop(NativePlayerLoopSystem*) (web.wasm:0x187fee)
    at MainLoop() (web.wasm:0x76c863)
    at dynCall_v (web.wasm:0x1976a2d)
    at web.framework.js:1036:20
    at browserIterationFunc (web.framework.js:9610:13)
    at callUserCallback (web.framework.js:7800:3)
    at Object.runIter (web.framework.js:7861:4)
    at Browser_mainLoop_runner (web.framework.js:7775:20)
```

**Comment by McJones** [comment] 2022-03-22 04:31
I think this and #151 may be related, they are both looking like IL2CPP build woes.
I am leaving this up for now as I do some more testing, but may close this and open a meta-issue or merge these issues instead if it turns out to be connected.

**Comment by McJones** [comment] 2022-03-23 02:30
ok so just for reference sake I also had some issues (not exactly the same but the same sort) in an IL2cpp webgl build.
In particular the same crash in what looks to be the ActionManager

**Comment by desplesda** [comment] 2022-04-04 03:07
Based on some spelunking through backtraces, I think I've found the call that's triggering this error: https://github.com/YarnSpinnerTool/YarnSpinner-Unity/blob/f3762fd6eb2f7e918c24bd68ea508977e83a2afd/Runtime/Commands/ActionManager.cs#L248

It's possible that the AOT compilation is doing something wrong?

**Comment by slonoed** [comment] 2022-04-09 03:53
<img width="683" alt="Screen Shot 2022-04-08 at 20 53 01" src="https://user-images.githubusercontent.com/463239/162555314-3c1521a5-cfd4-469a-b290-c8f10b3b7f34.png">

I found that this only happens when optimizing for faster runtime

**Comment by Cdddo** [comment] 2022-05-18 01:49
Just ran into the same issue. Can confirm if the IL2CPP Code Generation mode in the build settings is set to Faster runtime it crashes; setting it to Faster (smaller) builds works fine.

Running on Unity 2021.3.2

**Comment by desplesda** [comment] 2022-05-18 01:50
Ooh that's good info, thank you for this!

**Comment by Kaosumaru** [comment] 2022-06-12 11:33
I also encountered this issue. I would guess that this is some cryptic error in IL2CPP.
You can also reproduce this bug on win32 IL2CPP builds, so it's not exclusive to webGL platform.

While I was trying to analyze this, I encountered following behavior:

1. This crashes when func is `Func<float>`
```csharp
var func = GetFuncType(parameters.Length).MakeGenericType(paramTypes);
method.CreateDelegate(func);
```

2. But this doesn't crash:
```csharp
method.CreateDelegate(typeof(Func<float>));
```
Moreover, after calling 2, 1 stops crashing - maybe 2 is caching/instancing some data?


Based on this, I created a very ugly "hackfix"

```csharp
class Hackfixersample
{
    public static float StaticMethod(float a, int b)
    {
        return a + b;
    }
}

public class UnityHackfix : MonoBehaviour
{
    void Awake()
    {
        MethodInfo method = typeof(Hackfixersample).GetMethod("StaticMethod",
            BindingFlags.Public | BindingFlags.Static);

        FixInstances<float, float, float>(method);
        FixInstances<float, int, float>(method);
    }

    void FixInstances<T1, T2, T3>(MethodInfo method)
    {
        try
        {
            var x2 = Delegate.CreateDelegate(typeof(Func<T1, T2, T3>), method);
            Debug.Log($"Hackfixing {x2}...");
        }
        catch (Exception e)
        {
            Debug.Log($"Hackfixing {e}...");
        }
    }
}
```

**Comment by Kaosumaru** [comment] 2022-06-12 12:22
OK, not a fluke, I was just missing one step.

While I was trying to analyze this, I encountered following behavior:

This crashes when func is Func<float>

```csharp
var func = GetFuncType(parameters.Length).MakeGenericType(paramTypes);
method.CreateDelegate(func);
```

But this doesn't crash:
```csharp
method.CreateDelegate(typeof(Func<float>));
```
Moreover, after calling 2, 1 stops crashing - maybe 2 is caching/instancing some data?
No idea why `Faster (smaller) builds` helps, but without il2cpp source, is probably not possible to determine.

Based on this, I created a very ugly "hackfix"

```csharp
class Hackfixersample
{
    public static float StaticMethod(float a, int b)
    {
        return a + b;
    }
}

public class UnityHackfix : MonoBehaviour
{
    void Awake()
    {
        // Because of some arcane reason, 
        // `return method.CreateDelegate(GetFuncType(parameters.Length).MakeGenericType(paramTypes));`
        // doesn't work correctly, throwing exception with il2cpp::vm::InvokeDelegateConstructor

        // BUT if we call beforehand
        // `return method.CreateDelegate(typeof(Func<T1, T2...>));`
        // it starts working
        MethodInfo method = typeof(Hackfixersample).GetMethod("StaticMethod",
            BindingFlags.Public | BindingFlags.Static);

        FixInstances<float>(method);
        FixInstances<float, float, float>(method);
        FixInstances<float, int, float>(method);
    }

    void FixInstances<T1, T2, T3>(MethodInfo method)
    {
        try
        {
            var x2 = Delegate.CreateDelegate(typeof(Func<T1, T2, T3>), method);
            Debug.Log($"Hackfixing {x2}...");
        }
        catch (Exception e)
        {
            Debug.Log($"Hackfixing {e}...");
        }
    }

    void FixInstances<T1>(MethodInfo method)
    {
        try
        {
            var x2 = Delegate.CreateDelegate(typeof(Func<T1>), method);
            Debug.Log($"Hackfixing {x2}...");
        }
        catch (Exception e)
        {
            Debug.Log($"Hackfixing {e}...");
        }
    }
}

```

**Comment by Oarcinae** [comment] 2022-09-02 16:00
Just ran into this same thing. (Setting it to Faster (smaller) builds worked.)

**Comment by McJones** [comment] 2023-09-15 05:11
whoops this was meant to be closed months ago...

**Closed by McJones** 2023-09-15 05:11 UTC
Labels: bug
