### ISSUE TITLE
Calling DialogueRunner.StartDialogue(string startNode) from a Yarn Command does not start the new dialogue 

### ISSUE THREAD

**Issue by Haapavuo** [YarnSpinnerTool/YarnSpinner-Unity#18] opened 2020-06-29 14:07 UTC
**What is the current behavior?**
Dialogue UI vanishes and nothing happens. Dialogue does not continue from the new node.

**Please provide the steps to reproduce, and if possible a minimal demo of the problem**:
In .yarn, I run the following lines:
`<<set $returnNode to "TestNodeTitle">>`
`<<jumpTo {$returnNode}>>`

I have assigned `$returnNode` to be a name of another node where I want to jump.

`jumpTo` command calls `DialogueRunner.StartDialogue(nodeName)`.

Dialogue UI vanishes and nothing happens. Values are not assigned to Dialogue UI components.

**What is the expected behavior?**
Dialogue UI shows up showing the new node lines.

**Please tell us about your environment:**
  
  - Yarn Spinner Version: 1.2.6
  - Unity Version: 2019.3.6f1

**Comment by Haapavuo** [comment] 2020-06-29 14:29
A workaround is to add a small wait before calling StartDialogue():

`StartCoroutine(JumpToNodeCoroutine(parameters[0]));`

```
private IEnumerator JumpToNodeCoroutine(string nodeTitle)
{
    yield return new WaitForSeconds(0.01f);
    runner.StartDialogue(nodeTitle);
}
```

This works but it really should work without a delay too.

**Comment by naNuke** [comment] 2020-07-14 09:19
I have similiar script in my project but I stop the dialogue first, assign a node and then start it.
Works imidiately and without problems.

```
DialogueRunner.Stop();
DialogueRunner.startNode = nodeID;
DialogueRunner.StartDialogue();
```

Maybe doing it like this will work for you as well.

Other option why it works for me is maybe because my UIBehaviour is rewritten from scratch.
In case that swapping nodes instantly without waiting for next frame would be expected behaviour then this can be considered a bug and not a feature, which might be up to discussion with yarn devs.

**Comment by desplesda** [comment] 2021-07-09 06:57
This issue is caused by a dialogue runner being interrupted during the execution of a command. Changing nodes is a fairly specific case, so a better solution to this will be to add support for variables in the `<<jump>>` command.

I'll close this issue as `wontfix` (if you can't upgrade to Yarn Spinner 2.0 in your project, I suggest using the workaround that @naNuke suggested), and create a new issue for adding explicit support for it in the compiler.

Thanks for filing the issue!

**Closed by desplesda** 2021-07-09 06:57 UTC
Labels: bug
