### ISSUE TITLE
DialogueException: Cannot continue running dialogue. No node has been selected.

### ISSUE THREAD

**Issue by Bryan-Legend** [YarnSpinnerTool/YarnSpinner-Unity#262] opened 2024-01-08 19:48 UTC
Often after Runner.Dialogue.Stop(); is called I am seeing the following exception.

Could you please not throw an exception when dialog is stopped and using the standard LineView?
 
![image](https://github.com/YarnSpinnerTool/YarnSpinner-Unity/assets/920120/01bacda0-625c-4078-816f-c3f658ad7324)

**Comment by Bryan-Legend** [comment] 2024-01-08 19:49
This is using the latest 2.4.0 release.

DialogueException: Cannot continue running dialogue. No node has been selected.
Yarn.VirtualMachine.CheckCanContinue () (at <015661c7468d41c3b0a915d84199b7f6>:0)
Yarn.VirtualMachine.Continue () (at <015661c7468d41c3b0a915d84199b7f6>:0)
Yarn.Dialogue.Continue () (at <015661c7468d41c3b0a915d84199b7f6>:0)
Yarn.Unity.DialogueRunner.ContinueDialogue (System.Boolean dontRestart) (at ./Library/PackageCache/dev.yarnspinner.unity@2.4.0/Runtime/DialogueRunner.cs:1142)
Yarn.Unity.DialogueRunner.DialogueViewCompletedDismissal (Yarn.Unity.DialogueViewBase dialogueView) (at ./Library/PackageCache/dev.yarnspinner.unity@2.4.0/Runtime/DialogueRunner.cs:1217)
Yarn.Unity.DialogueRunner+<>c__DisplayClass111_0.<DismissLineFromViews>b__0 () (at ./Library/PackageCache/dev.yarnspinner.unity@2.4.0/Runtime/DialogueRunner.cs:1202)
Yarn.Unity.LineView+<DismissLineInternal>d__22.MoveNext () (at ./Library/PackageCache/dev.yarnspinner.unity@2.4.0/Runtime/Views/LineView.cs:278)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <30adf90198bc4c4b83910c6fb1877998>:0)

**Comment by McJones** [comment] 2024-01-10 03:55
I would recommend calling `Stop()` on the dialogue runner, not the dialogue itself.
While you can interface directly with the dialogue object it's not really got any safeguards on it, so what is happening is the dialogue is being stopped but then the line view isn't being told about it, and then is asking the runner to continue stopped dialogue which is throwing the exception.
The `Stop` method on the runner does tell views to dismiss themselves which will prevent this bug.
So use `Runner.Stop();` in place of `Runner.Dialogue.Stop();`.

I am going to close this issue as the solution is to not call stop on the dialogue but on the runner.
If you do want to talk directly to the dialogue object it's on you to make sure that important dialogue events are passed on to the different pieces that need to be informed about them.

**Comment by Bryan-Legend** [comment] 2024-01-10 05:58
Okay. I changed my code to call Runner.Stop instead, but unfortunately the bug is still happening.

The presence of LineView.DismissLineInternal high in the call stack (LineView.cs line 278) makes me think that the view dismissing itself is what is causing this issue. The code to dismiss the line view seems to be checking continue after it's already been stopped.

**Comment by Bryan-Legend** [comment] 2024-01-10 06:03
Also, here is the DialogueRunner.Stop method. It doesn't appear to be doing anything with the views.

`        /// <summary>
        /// Stops the <see cref="Dialogue"/>.
        /// </summary>
        public void Stop()
        {
            IsDialogueRunning = false;
            Dialogue.Stop();
        }`

**Comment by McJones** [comment] 2024-01-10 23:13
The `HandleDialogueComplete` method which is a dialogue event on the runner is what tells the views to dismiss, not Stop itself, but it is called as an effect of Stop being called.

If the issue is still happening though I will reopen the issue but can you give more information as to how you are triggering this?
Because when I stop dialogue in the middle of a line I don't get this error.

**Comment by Bryan-Legend** [comment] 2024-01-11 21:01
Yes. It's still happening. I'm wondering if HandleDialogComplete is not getting run for some reason.

I suspect that it has something to do with the Auto Advance setting on the Line View. The exception seems to happen about a half second after the dialog is skipped (via Runner.Stop) as shown in this screenshot console log time stamps. I also show my line view inspector so you can match my settings. 

![image](https://github.com/YarnSpinnerTool/YarnSpinner-Unity/assets/920120/fc6cf795-6b75-4d18-a1be-bda018f72b56)

![image](https://github.com/YarnSpinnerTool/YarnSpinner-Unity/assets/920120/c7b57de5-f43d-4697-a91a-deee51dd2c46)

**Comment by Bryan-Legend** [comment] 2024-01-11 21:22
I've confirmed that HandleDialogComplete is running and calling LineView.DialogueComplete correctly.

Also I've confirmed that the exception does not happen with Auto Advance off, but then sometimes text will be left on the screen after a cancel when Auto-Advance is turned off.

**Comment by McJones** [comment] 2024-01-12 00:31
thanks, investigating.

**Closed** 2024-01-19 02:33 UTC
Labels: bug

**Comment by Bryan-Legend** [comment] 2024-01-19 04:30
♥️
