### ISSUE TITLE
Updating yarn script with Unity remote config

### ISSUE THREAD

**Issue by jonathaniscarroll** [YarnSpinnerTool/YarnSpinner-Unity#41] opened 2020-09-27 17:10 UTC
I have a dream of creating new dialogue as my users progress through the game. 
Unity's Remote Config lets me update a string variable, where I can store the text of my yarn script and change it from unity dashboard. 
How do I update/recompile my yarn dialogue with this new string at runtime?

**Comment by radiatoryang** [comment] 2021-01-15 23:38
See issue #43 ... as I mentioned there, the current design of Yarn Spinner v2.0 is about precompiling in Unity Editor and avoiding runtime compilation. 

If you want to use v1.2.7 instead, then I believe runtime compilation is possible with DialogueRunner.AddScript() and you'd just need code to connect your Unity Remote Config to Yarn Spinner

Good luck!

**Comment by desplesda** [comment] 2021-07-09 06:21
Closing this issue as a duplicate of #43.

**Closed by desplesda** 2021-07-09 06:21 UTC
Labels: enhancement
