### ISSUE TITLE
Yarn Importer error with Unity (v2019.4.8f1)

### ISSUE THREAD

**Issue by Osailor** [YarnSpinnerTool/YarnSpinner-Unity#31] opened 2020-08-24 11:13 UTC
When installing the package version 1.2.6 on Unity 2019.4.8f1 Personal, the below console error appears relating to the YarnImportEditor script.

**YarnImporterEditor.OnInspectorGUI must call ApplyRevertGUI to avoid unexpected behaviour. UnityEditor.Experimental.AssetImporters.AssetImporterEditor:OnDisable()
YarnImporterEditor:OnDisable() (at Assets/YarnSpinner/Editor/YarnImporterEditor.cs:48)**

![YarnImportEditor error](https://user-images.githubusercontent.com/18251643/91038566-5409fe00-e64e-11ea-9032-edc0753b0c98.jpg)

**Comment by radiatoryang** [comment] 2020-09-05 21:58
I'm on Unity 2019.4.8f1 and I imported the 1.2.6 package... and I'm not seeing this error? You might need to provide more information to reproduce this bug.

**Comment by ChaosPhill** [comment] 2020-10-14 11:02
Don't know if anyone has checked this, but I got the same issue.
The problem seems to be with Yarn files being saved directly in the Unity project. If I save the Yarn file outside of the Unity project and then import it by drag & drop, then I don't get that issue and the Yarn file is correctly imported.
So I think the solution is just don't save inside Unity project.
Not sure if this is covered elsewhere. Sorry if it is.

**Comment by desplesda** [comment] 2021-07-09 06:19
I'm not currently seeing this issue in the `develop`, and this issue appears to not be blocking the workflow (it's just creating an annoying error in the console). As such, I'll close this here; if it reappears in 2.0, please re-open the issue! Thanks for filing this bug!

**Closed by desplesda** 2021-07-09 06:19 UTC
