### ISSUE TITLE
(Bug) YarnSpinner localization importer breaks inline variable usage

### ISSUE THREAD

**Issue by jzapdot** [YarnSpinnerTool/YarnSpinner-Unity#118] opened 2021-09-01 14:50 UTC
### What is the current behavior?
I've been attempting to use a simple test yarn script with the in-memory storage and branching logic appears to work fine with variables, but inline variables appear as format string indexes.

**Raw Yarn Script**
```


<<if $PlayerLevel is 2>>

Wow, you're Player Level is as high as {$PlayerLevel}?

<<elseif $PlayerLevel is 1>>

Ah, you're still Player Level {$PlayerLevel}?

<<endif>>

```

When executed, appears as `Ah, you're still Player Level {0}?`

It appears as if the variables are replaced by format string indexes in the localizations.

**Localization CSV Content**
```
id,text,file,node,lineNumber
line:0f12997,"Wow, you're Player Level is as high as {0}? (((NEW LINE)))",ScriptName,Start,10
line:0b99fc5,"Ah, you're still Player Level {0}? (((NEW LINE)))",ScriptName,Start,14
```

### Please provide the steps to reproduce, and if possible a minimal demo of the problem
1. Using the raw Yarn script above, save it as a `.yarn` file in a Unity project.
2. Select it in the inspector and run the localization importer.

### What is the expected behavior?

The inline variables should still be present in the localization and when the yarn script is run in Unity should be replaced with the variable's value.

### What is the actual behavior?

The inline variables are replaced in the localization with string indexes (like a format string) and when the yarn script is run in Unity the format strings are not replaced with the variable's value.

### Please tell us about your environment:
  
  - Yarn Spinner Version: `v1.2.6`
  - Unity Version: `2020.3.10f1`

### Additional context

![image](https://user-images.githubusercontent.com/40764984/131693324-3ccc3f59-7b40-472f-8ceb-435022e04721.png)

**Comment by desplesda** [comment] 2021-10-21 05:54
Replacing the contents of an inline expression with a placeholder is the expected behaviour; the placeholders not being replaced is unexpected.

**Comment by McJones** [comment] 2021-11-03 03:59
I can't reproduce this using a checkout from main, on Unity 2020.3.16 so a bit later than your version but I can't see how that would impact anything.
Does grabbing YS direct from main instead from the 1.2.6 release fix the issue?

**Comment by jzapdot** [comment] 2021-11-09 15:36
Hi @McJones, I apologize for the delayed response. We're in the final days to a significant milestone so it may take a week or so to be able to attempt a repro/further investigation.

**Comment by McJones** [comment] 2021-12-13 23:05
There's been no movement on these for a while now, closing them.
Feel free to reopen if the issue persists.

**Closed by McJones** 2021-12-13 23:05 UTC
Labels: bug
