### ISSUE TITLE
YarnNode Attribute doesn't display dropdown in certain data layouts.

### ISSUE THREAD

**Issue by unknowndevice** [YarnSpinnerTool/YarnSpinner-Unity#257] opened 2023-11-21 21:29 UTC
**What is the current behavior?**

Using the YarnNode Attribute doesn't display correctly in Arrays of objects. You can't select a node using the drop down. Instead it looks like this.

<img width="534" alt="Screenshot 2023-11-21 at 21 27 14" src="https://github.com/YarnSpinnerTool/YarnSpinner-Unity/assets/4682853/c75d306b-5c6c-4912-b4f3-09a35411cfd5">

**Please provide the steps to reproduce, and if possible a minimal demo of the problem**:

1. Create an editor script with the ActivityEditor class below
2. Create a scriptable script with the Activity script below
3. Create a scriptable
4. Click "Add Node Activity" and select Dialogue
5. Add a Yarn Project with Nodes
6. You'll now see the red warning with no way to select a node.

```csharp
#if UNITY_EDITOR

using UnityEditor;
using UnityEngine;
using Yarn.Unity;

namespace VideoGame.Editor
{
    [CustomEditor(typeof(Activity))]
    public class ActivityEditor : UnityEditor.Editor
    {
        public override void OnInspectorGUI()
        {
            DrawDefaultInspector();
            DrawNodesButton();

            if (Application.isPlaying || EditorApplication.isPlaying) return;

            void DrawNodesButton()
            {
                if (!GUILayout.Button("Add Node Activity")) return;

                GenericMenu menu = new();

                AddMenuItem(menu, "Battle", ActivityName.Battle);
                AddMenuItem(menu, "Dialogue", ActivityName.Dialogue);
                AddMenuItem(menu, "Side Activity", ActivityName.SideActivity);

                menu.ShowAsContext();

                void AddMenuItem(GenericMenu menu, string menuPath, ActivityName activityName)
                {
                    menu.AddItem(new GUIContent(menuPath), false, OnSelected, activityName);

                    void OnSelected(object activityName)
                    {
                        var yarn = (YarnProject)serializedObject.FindProperty("YarnProject").objectReferenceValue;
                        var nodes = serializedObject.FindProperty("Nodes");
                        var count = nodes.arraySize;
                        nodes.InsertArrayElementAtIndex(count);
                        var property = nodes.GetArrayElementAtIndex(count);

                        property.managedReferenceValue = (ActivityName)activityName switch {
                            ActivityName.Battle => new Activity.Battle { ActivityName = (ActivityName)activityName },
                            ActivityName.Dialogue => new Activity.Dialogue { ActivityName = (ActivityName)activityName, Node = string.Empty },
                            ActivityName.SideActivity => new Activity.SideActivity { ActivityName = (ActivityName)activityName },
                            _ => new Activity.Dialogue { ActivityName = (ActivityName)activityName, Node = string.Empty },
                        };

                        serializedObject.ApplyModifiedProperties();
                    }
                }
            }
        }
    }
}

#endif

using Assist;
using System;
using System.Collections.Generic;
using UnityEngine;
using Yarn.Unity;

namespace VideoGame
{
    public enum ActivityName { Battle = 0, Dialogue = 1, SideActivity = 2 };

    [CreateAssetMenu(menuName = "Activity")]
    public class Activity : ScriptableObject
    {
        [SerializeReference] public List<AcitivityNode> Nodes;

        [Serializable]
        public abstract class AcitivityNode
        {
#if UNITY_EDITOR
            [ReadOnly] public string Name;
#endif
            public ActivityName ActivityName;

            public abstract bool IsComplete();
        }

        [Serializable]
        public class Dialogue : AcitivityNode
        {
            public YarnProject Project;
            [YarnNode(nameof(Project))] public string Node;

            public override bool IsComplete() => false;

#if UNITY_EDITOR
            public Dialogue() => Name = "Dialogue";
#endif
        }

        [Serializable]
        public class Battle : AcitivityNode
        {
            public bool PlayBattleMusic = true;
            public ScriptableObject battle;

            public override bool IsComplete() => false;

#if UNITY_EDITOR
            public Battle() => Name = "Battle";
#endif
        }

        [Serializable]
        public class SideActivity : AcitivityNode
        {
            public string Node;
            public bool Unrepeatable;

            public override bool IsComplete() => false;

#if UNITY_EDITOR
            public SideActivity() => Name = "Side Activity";
#endif
        }
    }
}
```

**What is the expected behavior?**

The YarnNode Attribute dropdown listing all the Nodes should be displayed

**Please tell us about your environment:**
  
  - Yarn Spinner Version: 2.3.1
  - Unity Version: 2022.3.13f1

**Other information**

**Comment by McJones** [comment] 2024-01-19 03:42
I am having a bit of an issue reproducing this in Unity 2022 or 2021.

I had to slightly modify your editor script, in particular the line:
```csharp
var yarn = (YarnProject)serializedObject.FindProperty("YarnProject").objectReferenceValue;
```
will always cause a null reference exception because the `Activity` scriptable object doesn't have a `YarnProject` property.

Additionally I don't have the `Assist` include because I am not sure what that is, I assume something internal that wraps about the job system.
I am assuming this because you are using `[ReadOnly]` attributes.

Once I fixed those, by removing the `FindProperty` call and replacing `using Assist;` with `using Unity.Collections;` the node attribute works:

<img width="380" alt="Screen Shot 2024-01-19 at 2 34 30 pm" src="https://github.com/YarnSpinnerTool/YarnSpinner-Unity/assets/1658310/1e20d658-123d-4398-a5bf-50aab3184427">

I am including my slightly tweaked versions of `Activity` and `ActivityEditor`:
```csharp
#if UNITY_EDITOR

using UnityEditor;
using UnityEngine;
using Yarn.Unity;

namespace VideoGame.Editor
{
    [CustomEditor(typeof(Activity))]
    public class ActivityEditor : UnityEditor.Editor
    {
        public override void OnInspectorGUI()
        {
            DrawDefaultInspector();
            DrawNodesButton();

            if (Application.isPlaying || EditorApplication.isPlaying) return;

            void DrawNodesButton()
            {
                if (!GUILayout.Button("Add Node Activity")) return;

                GenericMenu menu = new();

                AddMenuItem(menu, "Battle", ActivityName.Battle);
                AddMenuItem(menu, "Dialogue", ActivityName.Dialogue);
                AddMenuItem(menu, "Side Activity", ActivityName.SideActivity);

                menu.ShowAsContext();

                void AddMenuItem(GenericMenu menu, string menuPath, ActivityName activityName)
                {
                    menu.AddItem(new GUIContent(menuPath), false, OnSelected, activityName);

                    void OnSelected(object activityName)
                    {
                        var nodes = serializedObject.FindProperty("Nodes");
                        var count = nodes.arraySize;
                        nodes.InsertArrayElementAtIndex(count);
                        var property = nodes.GetArrayElementAtIndex(count);

                        property.managedReferenceValue = (ActivityName)activityName switch {
                            ActivityName.Battle => new Activity.Battle { ActivityName = (ActivityName)activityName },
                            ActivityName.Dialogue => new Activity.Dialogue { ActivityName = (ActivityName)activityName, Node = string.Empty },
                            ActivityName.SideActivity => new Activity.SideActivity { ActivityName = (ActivityName)activityName },
                            _ => new Activity.Dialogue { ActivityName = (ActivityName)activityName, Node = string.Empty },
                        };

                        serializedObject.ApplyModifiedProperties();
                    }
                }
            }
        }
    }
}
#endif

using System;
using System.Collections.Generic;
using UnityEngine;
using Unity.Collections;
using Yarn.Unity;

namespace VideoGame
{
    public enum ActivityName { Battle = 0, Dialogue = 1, SideActivity = 2 };

    [CreateAssetMenu(menuName = "Activity")]
    public class Activity : ScriptableObject
    {
        [SerializeReference] public List<AcitivityNode> Nodes;

        [Serializable]
        public abstract class AcitivityNode
        {
#if UNITY_EDITOR
            [ReadOnly] public string Name;
#endif
            public ActivityName ActivityName;

            public abstract bool IsComplete();
        }

        [Serializable]
        public class Dialogue : AcitivityNode
        {
            public YarnProject Project;
            [YarnNode(nameof(Project))] public string Node;

            public override bool IsComplete() => false;

#if UNITY_EDITOR
            public Dialogue() => Name = "Dialogue";
#endif
        }

        [Serializable]
        public class Battle : AcitivityNode
        {
            public bool PlayBattleMusic = true;
            public ScriptableObject battle;

            public override bool IsComplete() => false;

#if UNITY_EDITOR
            public Battle() => Name = "Battle";
#endif
        }

        [Serializable]
        public class SideActivity : AcitivityNode
        {
            public string Node;
            public bool Unrepeatable;

            public override bool IsComplete() => false;

#if UNITY_EDITOR
            public SideActivity() => Name = "Side Activity";
#endif
        }
    }
}
```

But the issue now is I am no longer sure if what I am doing is actually reproducing your issue or fundamentally changing things.
Thoughts?

**Comment by McJones** [comment] 2024-02-01 02:24
It's been two weeks and there has been no movement on this issue.
I think my changes to your sample has fixed it so I am going to close this issue for now.
If the issue persists let me know and I can reopen it or you can file a new issue.

**Closed by McJones** 2024-02-01 02:24 UTC
Labels: bug
