### ISSUE TITLE
Using the color tag on text results in parsing errors and leaves the Yarn file unusable

### ISSUE THREAD

**Issue by HollowedEmpire** [YarnSpinnerTool/YarnSpinner-Unity#73] opened 2021-02-07 17:25 UTC
**What is the current behavior?**
Supplying a color tag on text causes a parsing error and leaves the Yarn file unusable.

**Please provide the steps to reproduce, and if possible a minimal demo of the problem**:
Simply take any text in a Yarn file, and encase it with the color tag - via manually or even through Yarn Editor. e.g. `<color=#000000>TEXT</color>`

**What is the expected behavior?**
To correctly parse the tag and apply the color to the text.

**Please tell us about your environment:**
  
  - Yarn Spinner Version: 1.2.7 (through Unity's Package Manager)
  - Unity Version: 2019.4.11f1
  - Yarn Editor version: 0.4.119 (where I used the color button to assign color to text)

**Other information** 
This behavior happens in any project - it currently effects both my own game, as well as the Space demo provided with Yarn.

The error appears to be related to the "#" symbol, as removing it will allow the Yarn file to be parsed and valid; though obviously the color tag will not work if this is done. Quite likely may be just a simple oversight since the localization tags also use the "#" symbol.

The error specifically reported is the following:
extraneous input '<' expecting {HASHTAG, BODY_HASHTAG, TEXT_NEWLINE, TEXT_HASHTAG, TEXT_COMMANDHASHTAG_HASHTAG, TEXT_COMMANDHASHTAG_NEWLINE, HASHTAG_TAG}
                          ^

**Comment by radiatoryang** [comment] 2021-02-16 02:34
Hello. Unfortunately this is by design -- the "#" is reserved for hashtag syntax, as defined in [the Yarn spec](https://github.com/YarnSpinnerTool/YarnSpinner/blob/yarn-spec/Documentation/Yarn-Spec.md). The Yarn Editor should probably get updated with alternatives.

For Unity, I suggest making use of the TextMeshPro stylesheets and tags instead, which lets you automatically insert HTML-style hex colors and formatting tags AFTER Yarn has processed the line. So for example, you could put `<red>This is important!</red>` in your Yarn script, and after YS sends the line into Unity, the Text Mesh Pro will automatically translate it into `<color=#FF0000>` equivalents. For more info, see: https://learn.unity.com/tutorial/textmesh-pro-style-sheets-and-styles

**Comment by radiatoryang** [comment] 2021-02-16 23:28
Hashtags are also an "industry standard" though? Arguably in greater use than hex colors today?

But anyway -- it seems you have strong feelings about this, so definitely voice your opinion on the PR for the Yarn specification soon before it gets permanently finalized: https://github.com/YarnSpinnerTool/YarnSpinner/pull/285

**Comment by HollowedEmpire** [comment] 2021-02-17 00:11
> Hashtags are also an "industry standard" though? Arguably in greater use than hex colors today?

Greater use than hex colors? I'd be very intrigued to see some proof behind that statement.

As for my claim about hex colors, you can open virtually any website's source, any game development engine (Unity, Game Maker, Unreal, etc), open any paint program, 3D modeling software, word processors... the list goes on and on of wildly varying application types that use hex colors. And least of all, you can open the _official Yarn Editor_ itself and notice it also uses hex colors. Obviously it does though, because it is a standard.

But that's not really the point I was making either, I was offering different solutions to resolve this issue. I only offered switching the symbol as an alternative solution if it seemed like "too much work" to parse the text, not for changing the symbol to be the main take away from my message. 

You also skipped over me pointing out that Yarn can easily cope with both uses for the hashtag if it did some basic parsing. There's no reason it can't be intelligent about using the hashtag if it is insisted to use it for line substitution too.

Though thank you, I certainly will bring this concern up to help Yarn not completely botch supporting basic color functionality. It certainly deserves to not have such a sore spot put on it for no reason. I'm only floored it hasn't been addressed long ago. I can't be the only one in the world interested in colored font support.

**Comment by desplesda** [comment] 2021-03-07 01:08
As of YarnSpinnerTool/YarnSpinner@f1dc0ee2d, Yarn Spinner now supports escaping the `#` character, so if have existing systems that expect to see colours as `#ff00ff` (i.e. with a hash at the start), you can express it like this:

```
Me: wow I'm <color=\#ff00ff>purple</color>
```

Yarn Spinner will deliver this line to your game like this (removing the `\`):

```
Me: wow I'm <color=#ff00ff>purple</color>
```

This feature will ship in the next release of Yarn Spinner.

I'll close this issue now, since I believe this resolves the issue as originally posted. Thanks for filing it!

**Closed by desplesda** 2021-03-07 01:08 UTC
Labels: bug
