### ISSUE TITLE
Line View Auto-Completes All Other Lines if Continue Action Key is Used

### ISSUE THREAD

**Issue by some1chan** [YarnSpinnerTool/YarnSpinner-Unity#147] opened 2022-01-12 08:21 UTC
**What is the current behavior?**

When pressing the continue action key in the new Input System, this causes the rest of the dialogue (unless `<<wait>>` gets called) to all auto-complete the typewriter effect the same frame new text is shown.

**Please provide the steps to reproduce, and if possible a minimal demo of the problem**:

1. Import the Visual Novel example, and enter the VisualNovel scene
2. Import the new Input System in the Package Manager, then enable it
3. In the inspector, go to VisualNovelPrefab -> Dialogue Canvas -> Dialogue Panel, then make the changes to the LineView inspector variables:
    - Set Continue Action Type from "Key Code" to "Input System Action"
    - Add a new Binding, and set it to the Space Key on Keyboard
    - Optional, but makes this bug _much_ more visible; set the Typewriter Effect Speed from 80 to 20
4. Optional: go to VisualNovelPrefab -> EventSystem, then switch it to the new system. This will stop error messages popping up every frame. 
5. Press Play
6. Press the Space key, then press it again

**What is the expected behavior?**

The continue input will work like the legacy Input System, or clicking in the new Input System, in where skipping the typewriter effect the first time doesn't make all the other dialogue skip the typewriter effect.

**Please tell us about your environment:**
  
  - Yarn Spinner Version: 2.0.2
  - Unity Version: 2019.4.34f1

**Other information** 

This happens because one key press triggers the `UserPerformedSkipAction()` function twice (I think, I might've been remembering wrong). This causes `LineView.cs` to display the next line, and also finish the typewriter effect the same frame.

This bug may also cause it to auto-select a dialogue option, too. This may be unrelated, but is reproducible in this environment, and not reproducible with the legacy input system.

**Comment by McJones** [comment] 2022-03-24 00:13
I am unable to reproduce this bug in YS 2.1, as part of that release in PR #139 there was a lot of changes to how the input system is handled.
I am closing this for now, feel free to open a new issue if the problem persists.

Also thank you for the fantastically detailed issue and steps.

**Closed by McJones** 2022-03-24 00:13 UTC
Labels: bug
